# Generated by Django 5.1.7 on 2025-04-01 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorados',
            old_name='Navigators',
            new_name='navigators',
        ),
        migrations.RenameField(
            model_name='mentorados',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='mentorados',
            old_name='User',
            new_name='user',
        ),
    ]
