# Generated by Django 5.1.7 on 2025-04-01 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0002_rename_navigators_mentorados_navigators_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorados',
            old_name='navigators',
            new_name='navigator',
        ),
    ]
